apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - kustomization-config-mq.yaml

# Set the namespace for all resources
namespace: mq

# Generate the ConfigMap resources from the raw MQSC file
configMapGenerator:
  - name: myqm-config
    files:
      - myqm.mqsc
      - myqm.ini

# Include QM resource
resources:
  - myqm.yaml
# generators:
#   # load secret from file
#   - my-tls-secret-extfile.yaml
#
#   - name: mq-truststore-secret
#     files:
#     - app2.crt
#   type: Opaque
#   - name: mq-tls-secret
#     files:
#     - tls.crt=new-certs/tls.crt
#     - tls.key=new-certs/tls.key
#   type: kubernetes.io/tls
