apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: myqm-native
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: NonProduction
  queueManager:
    availability:
      type: NativeHA
    mqsc:
      - configMap:
          name: myqm-config
          items:
            - myqm.mqsc
    ini:
      - configMap:
            name: myqm-config
            items:
              - myqm.ini
  version: 9.4.3.0-r2
  web:
    enabled: false
