apiVersion: mq.ibm.com/v1beta1
kind: QueueManager

metadata:
  name: qm1
  annotations:
    "mq.ibm.com/stop" : "false"
spec:
  license:
    accept: true
    license: L-CYPF-CRPF3H
    use: NonProduction
  queueManager:
    name: QM1
    metrics:
      enabled: true
      tls:
        provider: openshift
    # ini:
    #   - configMap:
    #       name: example-06-qm6-configmap
    #       items:
    #         - qm6.ini
    mqsc:
    - configMap:
        name: mqsc-configmap
        items:
        - static-definitions.mqsc

    availability:
      type: NativeHA
    # resources:
    #   limits:
    #     cpu: 3000m
    #     memory: 1000Mi
    #   requests:
    #     cpu: 2000m
    #     memory: 500Mi
    storage:
      defaultClass: gp2
      persistedData:
        enabled: false
      queueManager:
        size: 2Gi
        type: persistent-claim
      recoveryLogs:
        enabled: false

  version: 9.4.3.0-r2
  pki:
    keys:
      - name: qm1
        secret:
          secretName: tls-secret-12012026
          items:
          - tls.key
          - tls.crt
  web:
    console:
      authentication:
        provider: manual
      authorization:
        provider: manual
    manualConfig:
      configMap:
        name: mqweb-configmap
    enabled: true        
  # web:
  #   console:
  #     authentication:
  #       provider: manual
  #     authorization:
  #       provider: manual
  #   manualConfig:
  #     configMap:
  #       name: mqwebuserconfigmap
  #   enabled: true
  # template:
  #   pod:
  #     containers:
  #       - env:
  #           - name: MQ_CONNAUTH_USE_HTP
  #             value: 'true'
  #           - name: MQ_DEV
  #             value: 'true'
  #           - name: MQ_ADMIN_PASSWORD
  #             valueFrom:
  #               secretKeyRef:
  #                 name: qmdemo-passwords
  #                 key: dev-app-password
  #           - name: MQ_APP_PASSWORD
  #             valueFrom:
  #               secretKeyRef:
  #                 name: qmdemo-passwords
  #                 key: dev-app-password
  #         name: qmgr
  # pki:
  #   keys:
  #     - name: example
  #       secret:
  #         secretName: example-06-qm6-secret
  #         items:
  #         - tls.key
  #         - tls.crt
  #   trust:
  #   - name: app1
  #     secret:
  #       secretName: example-06-app1-secret
  #       items:
  #         - app1.crt
  
